apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc3s-b2x-asmo-productcatalog-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GITOPS_REPOSITORY_URL
    targetRevision: main
    path: openshift/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: REPLACE_WITH_DEV_NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
