stages:
    - pre-commit
    - code_quality
    - security_scans
    - build
    - container_scan
    - deploy
    - post-deploy
include:
    - 01-pre-commit/Check_Main_Updates.yaml
    #- 01-pre-commit/Lint_Test.yml
    - 02-code-quality/Code_Quality.yaml
    - 02-code-quality/Code_Quality_html.yaml
    - 03-security_scans/Static_Application_Security_Test.yaml
    - 03-security_scans/Dependency-Scanning.yaml
    - 03-security_scans/secret-detection.yml  
    - 04-build/Build_Application.yaml
    - 04-build/Build_Docker_Image.yaml
    - 05-container_scan/Container-Scanning.yaml
    - 06-deploy/Deploy-Dev.yaml
    - 06-deploy/Deploy-Test.yaml
    - 06-deploy/Deploy-Mig.yaml
    - 06-deploy/Deploy-Preprod.yaml
    - 06-deploy/Deploy-Prod.yaml
    - 06-deploy/Deploy-Npe1.yaml
    - 06-deploy/Deploy-4env.yaml
    - 07-post-deploy/Trigger_Test_Automation.yaml
