kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ./../../base
  - serviceaccount.yaml

patches:
  - target:
      kind: Deployment
      group: apps
      version: v1
      name: mc3s-b2x-aggregator-productcatalog
    patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: mc3s-b2x-aggregator-productcatalog
      - op: remove
        path: /spec/selector/matchLabels/name
      - op: remove
        path: /spec/template/metadata/labels/name
  - target:
      kind: Service
      version: v1
      name: mc3s-b2x-aggregator-productcatalog
    patch: |-
      - op: remove
        path: /spec/selector/name

  - target:
      kind: HorizontalPodAutoscaler
      group: autoscaling
      version: v2
      name: mc3s-b2x-aggregator-productcatalog
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
configMapGenerator:
  - name: aggregator-config
    envs:
    - app.env
