apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::**********:role/b2x-mc3s-b2x-aggregator-productcatalog
  name: mc3s-b2x-aggregator-productcatalog
