apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: asmo-app-client
  namespace: asmo-kafka-dev
  labels:
    strimzi.io/cluster: asmo-dev-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: asmo.
          patternType: prefix
        operations:
          - Create
          - Describe
          - Read
          - Write
          - DescribeConfigs
          - AlterConfigs
        host: "*"
      - resource:
          type: topic
          name: canary.
          patternType: prefix
        operations:
          - Create
          - Describe
          - Read
          - Write
          - DescribeConfigs
          - AlterConfigs
        host: "*"
      - resource:
          type: group
          name: asmo-app
          patternType: prefix
        operations:
          - Read
        host: "*"
