apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - route.yaml
  - serviceaccount.yaml

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: mc3s-b2x-aggregator-productcatalog
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        name: mc3s-b2x-aggregator-productcatalog
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: mc3s-b2x-swagger-productcatalog
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        name: mc3s-b2x-swagger-productcatalog
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: mc3s-b2x-aggregator-productcatalog
    patch: |-
      $patch: delete
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: mc3s-b2x-aggregator-productcatalog
  - target:
      group: external-secrets.io
      version: v1alpha1
      kind: SecretStore
      name: secrets
    patch: |-
      $patch: delete
      apiVersion: external-secrets.io/v1alpha1
      kind: SecretStore
      metadata:
        name: secrets

configMapGenerator:
  - name: aggregator-config
    envs:
      - app.env

images:
  - name: custom_image
    newName: nexus.apps.asmonpeclr.np.asmo.com/marketplace/mc3s-b2x-asmo-productcatalog
    newTag: ocp
