apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - route.yaml
  - serviceaccount.yaml

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml

configMapGenerator:
  - name: aggregator-config
    envs:
      - app.env

secretGenerator:
  - name: ct-secret
    envs:
      - ct-secret.properties

images:
  - name: custom_image
    newName: nexus.apps.asmonpeclr.np.asmo.com/marketplace/mc3s-b2x-asmo-productcatalog
    newTag: ocp
