<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mindcurv.b2x.productcatalog</groupId>
        <artifactId>mc3s-b2x-productcatalog</artifactId>
        <version>0-SNAPSHOT</version>
    </parent>

    <artifactId>mc3s-app-aggregator-productcatalog</artifactId>
    <version>0-SNAPSHOT</version>
    <packaging>jar</packaging>


    <properties>
        <version>${project.version}</version>
        <start-class>com.mindcurv.b2x.Mc3sRunnerApp</start-class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.mindcurv.b2x.productcatalog</groupId>
            <artifactId>mc3s-b2x-aggregator-productcatalog</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mindcurv.b2x.commons</groupId>
            <artifactId>mc3s-b2x-adapter-commercetools</artifactId>
            <version>${mc3s-b2x-commons.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mindcurv.b2x.productcatalog</groupId>
            <artifactId>mc3s-b2x-aggregator-productreview</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mindcurv.b2x.cloud</groupId>
            <artifactId>mc3s-b2x-cloud-all</artifactId>
            <version>${mc3s-b2x-cloud.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mindcurv.b2x.commons</groupId>
            <artifactId>mc3s-b2x-commons-all</artifactId>
            <version>${mc3s-b2x-commons.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>${logstash-logback-encoder.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>${jakarta.xml.bind-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.intuit.karate</groupId>
            <artifactId>karate-junit5</artifactId>
            <version>${karate-junit5.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>${caffeine-cache.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>${pitest-maven.version}</version>
                <configuration>
                    <skip>${pitest.execution.skip}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>put-pit-together</id>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>${pitest-junit5-plugin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <addResources>true</addResources>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib-maven-plugin.version}</version>
                <configuration>
                    <container>
                        <mainClass>com.mindcurv.b2x.Mc3sRunnerApp</mainClass>
                        <creationTime>${maven.build.timestamp}</creationTime>
                        <jvmFlags>
                            <jvmFlag>-Xms512m</jvmFlag>
                        </jvmFlags>
                    </container>
                    <from>
                        <image>gcr.io/distroless/java21:latest</image>
                    </from>
                    <to>
                        <image>
                            008535898960.dkr.ecr.eu-central-1.amazonaws.com/mc3s-b2x-aggregator-productcatalog-dev:1.00
                        </image>
                    </to>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
