FROM registry.redhat.io/amq-streams/kafka-42-rhel9:3.2.0

COPY --chown=1001:0 scripts/test-external-kafka-client.sh /opt/kafka/test-external-kafka-client.sh
COPY --chown=1001:0 --chmod=0644 build-assets/asmo-kafka-test-truststore.jks /opt/kafka/test-truststore/truststore.jks
COPY --chown=1001:0 --chmod=0644 build-assets/truststore.password /opt/kafka/test-truststore/truststore.password
RUN command -v keytool && command -v openssl && bash -n /opt/kafka/test-external-kafka-client.sh

CMD ["sleep", "3600"]
