<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mindcurv.b2x.productcatalog</groupId>
        <artifactId>mc3s-b2x-productcatalog</artifactId>
        <version>0-SNAPSHOT</version>
    </parent>

    <artifactId>mc3s-b2x-productreview-models</artifactId>
    <version>0-SNAPSHOT</version>
    <packaging>jar</packaging>


    <properties>
        <version>${project.version}</version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.mindcurv.b2x.commons</groupId>
            <artifactId>mc3s-b2x-base</artifactId>
            <version>${mc3s-b2x-commons.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mindcurv.b2x.commons</groupId>
            <artifactId>mc3s-b2x-commerce-models</artifactId>
            <version>${mc3s-b2x-commons.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>${pitest-maven.version}</version>
                <configuration>
                    <skip>${pitest.execution.skip}</skip>
                    <exportLineCoverage>true</exportLineCoverage>
                    <excludedClasses>${pitest.excludedClasses}</excludedClasses>
                    <mutationThreshold>${pitest.mutationThreshold}</mutationThreshold>
                    <coverageThreshold>${pitest.coverageThreshold}</coverageThreshold>
                    <skipFailingTests>${pitest.skipFailingTests}</skipFailingTests>
                    <timeoutConstant>${pitest.timeoutConstant}</timeoutConstant>
                    <failWhenNoMutations>${pitest.failWhenNoMutations}</failWhenNoMutations>
                    <outputFormats>
                        <outputFormat>CSV</outputFormat>
                        <outputFormat>XML</outputFormat>
                        <outputFormat>HTML</outputFormat>
                    </outputFormats>
                    <sourceDataFormats>
                        <sourceDataFormat>HTML</sourceDataFormat>
                    </sourceDataFormats>
                    <siteReportDirectory>pit</siteReportDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>run-mutation-tests</id>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>${pitest-junit5-plugin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate_datamodel</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/${project.artifactId}.yaml
                            </inputSpec>
                            <templateResourcePath>${project.basedir}/../templates/resttemplate
                            </templateResourcePath>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <sourceFolder>src/main/java</sourceFolder>
                                <serializableModel>true</serializableModel>
                                <interfaceOnly>true</interfaceOnly>
                                <useBeanValidation>true</useBeanValidation>
                                <useOptional>false</useOptional>
                                <useTags>true</useTags>
                                <dateLibrary>java8</dateLibrary>
                                <useJakartaEe>true</useJakartaEe>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                            <modelPackage>${project.groupId}.review.models</modelPackage>
                            <apiPackage>${project.groupId}.review.api</apiPackage>
                            <invokerPackage>${project.groupId}.review.invoker</invokerPackage>
                            <output>${project.build.directory}/generated-sources</output>
                            <generatorName>spring</generatorName>
                            <library>spring-boot</library>
                            <generateApis>true</generateApis>
                            <generateApiTests>false</generateApiTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateSupportingFiles>true</generateSupportingFiles>
                            <generateAliasAsModel>true</generateAliasAsModel>
                            <importMappings>
                                <importMapping>
                                    PageableOfProductReviewAggregation=com.mindcurv.b2x.productcatalog.review.openapi.PageableOfProductReviewAggregation
                                </importMapping>
                                <importMapping>Reference=com.mindcurv.b2x.commons.models.Reference
                                </importMapping>
                                <importMapping>
                                    StateAggregation=com.mindcurv.b2x.commons.models.StateAggregation
                                </importMapping>
                            </importMappings>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

