apiVersion: v1
kind: Pod
metadata:
  name: kafka-external-cert-smoke
  namespace: asmo-kafka-dev
spec:
  restartPolicy: Never
  containers:
    - name: kafka-client
      image: docker.io/waleednabeeh/asmo-kafka-smoke:2026-09-18-2
      imagePullPolicy: Always
      command: ["sleep", "3600"]
      volumeMounts:
        - name: user-secret
          mountPath: /opt/kafka/user
          readOnly: true
  volumes:
    - name: user-secret
      secret:
        secretName: asmo-app-client
