---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mc3s-b2x-aggregator-productcatalog
  annotations:
    reloader.stakater.com/match: "true"
spec:
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: mc3s-b2x-aggregator-productcatalog-commercetools-credentials
  secretStoreRef:
    name: secrets
    kind: SecretStore
  target:
    name: ct-secret # Secret name in k8s
